version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: iot
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d iot"]
      interval: 5s
      retries: 20
    restart: unless-stopped
    networks:
      - default

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: iot
      DB_PORT: 5432
    restart: unless-stopped
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-router.rule=PathPrefix(`/s65114540754`)"
      - "traefik.http.routers.backend-router.middlewares=backend-strip-prefix"
      - "traefik.http.middlewares.backend-strip-prefix.stripprefix.prefixes=/s65114540754"
      - "traefik.http.services.backend-service.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik-public"

volumes:
  db_data:

networks:
  default:
    driver: bridge
  traefik-public:
    external: true